### PR TITLE
Allow passing Printer to GoldenCodecTests

### PR DESCRIPTION
**Pull request by fredfp**
ref: #56

### CODE REVIEW

**Comment by fredfp** [comment]
I did something quickly, I'm not sure what's best to deal with the optional/default parameters here, let me know what your thoughts are.

I have no good ideas to improve the code coverage situation, just a few ideas of how to work around that. What are you expecting?

**Comment by travisbrown** [comment]
This looks reasonable to me, and the slight code coverage drop isn't a big deal. I'll try to take a closer look and get it merged this weekend.

**Comment by travisbrown** [comment]
Also thanks!

**Comment by fredfp** [comment]
Hello @travisbrown , do you have any feedback or doubts?

I'd love to move forward with that as it'll make implementation of circe-golden much easier in some of our bigger projects

**Comment by travisbrown** [comment]
@fredfp The one thing I still wanted to look at is making `sbt mimaReportBinaryIssues` pass, so that we don't need to bump the minor version, but I don't think that's a big deal, and will go ahead and merge.

**Comment by fredfp** [comment]
Thank you!

**Pull request merged**
